#!/bin/bash
autoreconf -fi

emconfigure ./configure \
--with-oniguruma=builtin \
--disable-maintainer-mode

emmake make LDFLAGS=-all-static

#make  -f Makefile.PHONY.wasm  clean
# working
# emcc -Os  main.c -o idbfs.mjs \
#  -s WASM=1 \
#  -s FORCE_FILESYSTEM=1 \
#  -lidbfs.js \
#  -s USE_ZLIB=1 \
#  -s INVOKE_RUN=0 \
#  -s EXTRA_EXPORTED_RUNTIME_METHODS=['FS','callMain'] \
#  -s MODULARIZE=1 \
#  -s EXPORT_ES6=1

# emcc -Os  main.c -o afs.js \
#  -s WASM=1 \
#  -s FORCE_FILESYSTEM=1 \
#  -lidbfs.js \
#  -s USE_ZLIB=1 \
#  -s ASSERTIONS=1 \
#  -s INVOKE_RUN=0 \
#  -s EXTRA_EXPORTED_RUNTIME_METHODS=['FS','callMain'] \

#emcc -Os  main.c -o wmfs.js \
# -s WASM=1 \
# -lworkerfs.js \
# -s USE_ZLIB=1 \
# -s INVOKE_RUN=0


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# FLAGS="-Os -g4 \
# -s FORCE_FILESYSTEM=1 \
# -lidbfs.js \
# -s USE_ZLIB=1 \
# --source-map-base http://127.0.0.1:8887/ \
# --preload-file package.json@/package.json \
# -s ASYNCIFY=1 \
# -s INVOKE_RUN=0 \
# -s NO_EXIT_RUNTIME=1 \
# -s EXTRA_EXPORTED_RUNTIME_METHODS=['FS','callMain'] \
# "

#source map -g4 --source-map-base http://127.0.0.1:8887/ \


#FLAGS="-Os -g4 \
#-s FORCE_FILESYSTEM=1 \
#-lidbfs.js \
#-s USE_ZLIB=1 \
#--source-map-base http://127.0.0.1:8887/ \
#--preload-file package.json@/package.json \
#-s ASYNCIFY=1 \
#-s INVOKE_RUN=0 \
#-s NO_EXIT_RUNTIME=1 \
#-s EXTRA_EXPORTED_RUNTIME_METHODS=['FS','callMain'] \
#"

#emmake make \
#LDFLAGS_native="$FLAGS" \
#CC_native=emcc  \
#EXE_native=index.html \
#CFLAGS_native="$FLAGS"